---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xsx/public_html/
    - /bin/cp -rf .htaccess "$DEPLOYPATH"
    - /bin/cp -rf _init.php "$DEPLOYPATH"
    - /bin/cp -rf index.php "$DEPLOYPATH"
    - /bin/cp -rf track.php "$DEPLOYPATH"
    - /bin/cp -rf health.php "$DEPLOYPATH"
    - /bin/cp -rf admin "$DEPLOYPATH"
